[package]
name = "mah_ts_identity"
version = "1.0.0"
authors = ["Splamy <splamyn@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
#flakebi-ring = "0.16.9"
#failure = "0.1.6"
tsproto = { path = "../tsclientlib/tsproto", version="=0.1.0" }
rayon = "1.3.0"
structopt = "0.3.8"
