[package]
name = "mah_ts_identity"
version = "1.0.0"
authors = ["Splamy <splamyn@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
base64 = "0.10"
rayon = "1.3.0"
structopt = "0.3.8"
tsproto = { path = "../tsclientlib/tsproto", version="=0.1.0" }
byteorder = "1.3.2"
